config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'toy_robots#home'

  resources :toy_robots, only: [:show] do
    collection do
      post :simulate
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/compass.rb
class Compass
  DIRECTIONS = %w(EAST WEST NORTH SOUTH).freeze

  LEFT_MOVE_MAPPINGS_90_DEGREE = {
    DIRECTIONS[0] => 'NORTH',
    DIRECTIONS[1] => 'SOUTH',
    DIRECTIONS[2] => 'WEST',
    DIRECTIONS[3] => 'EAST'
  }

  RIGHT_MOVE_MAPPINGS_90_DEGREE = {
    DIRECTIONS[0] => 'SOUTH',
    DIRECTIONS[1] => 'NORTH',
    DIRECTIONS[2] => 'EAST',
    DIRECTIONS[3] => 'WEST'
  }

  def self.move_left(direction)
    LEFT_MOVE_MAPPINGS_90_DEGREE[direction]
  end

  def self.move_right(direction)
    RIGHT_MOVE_MAPPINGS_90_DEGREE[direction]
  end

end

app/models/document.rb
class Document < ApplicationRecord
  mount_uploader :name, DocumentUploader

  # Validations
  validates :name, presence: true

end

app/models/table.rb
class Table < ApplicationRecord

  # Associations
  validates :width,
            numericality: { only_integer: true, greater_than: 0 }

  validates :height,
            numericality: { only_integer: true, greater_than: 0 }
end

app/models/toy_robot.rb
class ToyRobot < ApplicationRecord

  # Associations
  validates :full_name, presence: true
  validates :position_x, :position_y, 
            numericality: { only_integer: true, greater_than_or_equal_to: 0 },
            allow_nil: true

  validates :direction, 
            inclusion: { in: Compass::DIRECTIONS },
            allow_nil: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	rescue_from ActionController::ParameterMissing, with: :param_missing_err_handler

	def param_missing_err_handler
		redirect_to root_path
	end

end

app/controllers/toy_robots_controller.rb
class ToyRobotsController < ApplicationController
  before_action :fetch_toy_robot_and_table, except: [:show]

  def home
    @toy_robot.update({ position_x: nil, position_y: nil, direction: nil}) if @toy_robot.present?
  end

  def simulate
    # Read file and perform operations accordingly
    document = Document.new(document_params)
    if document.valid?
      FileCommandProcessor.new(document).process(@toy_robot, @table)
      redirect_to toy_robot_path(id: @toy_robot.id)
    else
      flash[:error] = 'Testing error message'
      redirect_to root_path
    end
  end

  def show
    @toy_robot = ToyRobot.find_by_id params[:id]
  end

  private

  def fetch_toy_robot_and_table
    @toy_robot = ToyRobot.first
    @table = Table.first
  end

  def document_params
    params.require(:document).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/toy_robots_helper.rb
module ToyRobotsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToyrobotSimulator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application/_flash_message.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="fm-alert text-center alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %> flash-msg js-flash-msg">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/toy_robots/home.html.erb
<h2>Welcome to ToyRobot Simulator</h2>
<h4>Upload the text file containing the ToyRobot simulation instructions</h4>
<%= form_tag(simulate_toy_robots_path, 
      :method => 'POST',
      multipart: true,
      :class => 'form-horizontal') do %>

  <div>
      <%= file_field_tag 'document[name]', accept: '.txt' %>
  </div>

  <div style='margin-top: 20px;'>
      <button type="submit" class="btn btn-default aasabtn text-uppercase">Upload</button>
  </div>    
<% end %>      

app/views/toy_robots/show.html.erb
<h2>Current position of ToyRobot </h2>
<div style="margin-top:18px;">
  <h4><%= "X = #{@toy_robot.position_x}, Y = #{@toy_robot.position_y}, Direction = #{@toy_robot.direction}" %></h4>
</div>

<div style="margin-top:18px;"><%= link_to 'Home', root_path %></div>